# Form implementation generated from reading ui file 'todo.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 301)
        self.taskEdit = QtWidgets.QLineEdit(parent=Form)
        self.taskEdit.setGeometry(QtCore.QRect(60, 50, 113, 20))
        self.taskEdit.setObjectName("lineEdit")
        
        self.addTaskButton = QtWidgets.QPushButton(parent=Form)
        self.addTaskButton.setGeometry(QtCore.QRect(190, 50, 75, 23))
        self.addTaskButton.setObjectName("pushButton")
        
        self.deleteButton = QtWidgets.QPushButton(parent=Form)
        self.deleteButton.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.deleteButton.setObjectName("pushButton_2")
        
        self.taskList = QtWidgets.QListWidget(parent=Form)
        self.taskList.setGeometry(QtCore.QRect(60, 90, 291, 192))
        self.taskList.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addTaskButton.setText(_translate("Form", "Add"))
        self.deleteButton.setText(_translate("Form", "Delete"))
